version: "3.8"

services:
  test-mysql:
    image: mysql:8.0.34
    container_name: oz-mysql
    ports:
      - "3306:3306"
    volumes:
      - ./conf.d:/etc/mysql/conf.d
      - ./init:/docker-entrypoint-initdb.d
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: oz
      MYSQL_PASSWORD: oz
      MYSQL_DATABASE: oz
